baseURL = 'https://dev.ianmcg.dev/'
languageCode = 'en-us'
title = 'Ian McGillivary'
theme = "gokarna-custom"

[params]
    avatarURL = "/images/avatar.webp"
    description = "An aspiring software developer"
    socialIcons = [
        {name = "linkedin-feather", url = "https://www.linkedin.com/in/ian-mcgillivary/"},
        {name = "github-feather", url = "https://github.com/Wiian16"},
        {name = "mail", url = "mailto:ianmcgil@iu.edu"},
        {name = "file-text", url="https://assets.ianmcg.dev/public/IanMcGillivaryResume.pdf"}
    ]
    customHeadHTML = '''
        <link rel="stylesheet" href="/css/style.css">
    '''

[menu]
    [[menu.main]]
        name = "Home"
        pre = "<span data-feather='home'></span>"
        pageRef = "/"
        weight = 1

    [[menu.main]]
        name = "Projects"
        pre = "<span data-feather='code'></span>"
        pageRef = "/projects/"
        weight = 2

    [[menu.main]]
        name = "Tags"
        pre = "<span data-feather='tag'></span>"
        pageRef = "/tags/"
        weight = 3

    [[menu.main]]
        name = "Github"
        pre = "<span data-feather='github'></span>"
        url = "https://github.com/Wiian16"
        weight = 4
    
    [[menu.main]]
        name = "Resume"
        pre = "<span data-feather='file-text'></span>"
        url = "https://assets.ianmcg.dev/public/IanMcGillivaryResume.pdf"
        weight = 4
