baseURL = 'https://dev.ianmcg.dev/'
languageCode = 'en-us'
title = 'Ian McGillivary'
theme = "gokarna"

[params]
    avatarURL = "/images/avatar.webp"
    description = "An aspiring software developer"
    customHeadHTML = '''
        <link rel="stylesheet" href="/css/style.css">
    '''

[menu]
    [[menu.main]]
        name ="About Me"
        url = "/about-me"
        weight = 1
