baseURL = 'https://dev.ianmcg.dev/'
languageCode = 'en-us'
title = 'Ian McGillivary'
theme = "gokarna-custom"

[params]
    avatarURL = "/images/avatar.webp"
    description = "An aspiring software developer"
    socialIcons = [
        {name = "linkedin", url = "https://www.linkedin.com/in/ian-mcgillivary/"},
        {name = "github", url = "https://github.com/Wiian16"},
        {name = "mail", url = "mailto:ianmcgil@iu.edu"},
        {name = "file-text", url="https://assets.ianmcg.dev/public/IanMcGillivaryResume.pdf"}
    ]
    customHeadHTML = '''
        <link rel="stylesheet" href="/css/style.css">
    '''

[menu]
